num_steps: 50000000  # It equals to 200M frames.
batch_size: 128
N: 32
kappa: 1.0
lr: 5.e-5
memory_size: 1000000
gamma: 0.99
multi_step: 1
update_interval: 4
target_update_interval: 10000
start_steps: 50
epsilon_train: 0.01
epsilon_eval: 0.001
epsilon_decay_steps: 250000  # It equals to 1M frames.
use_per: False
max_episode_steps: 36
grad_cliping:
